# Generated by Django 5.2.12 on 2026-03-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_cart_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
