# Generated by Django 6.0.3 on 2026-03-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_category_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price_per_unit",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kg", "kg"),
                    ("liter", "liter"),
                    ("bundle", "bundle"),
                    ("piece", "piece"),
                ],
                default="kg",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
